### ISSUE TITLE
Add a chat prefixes system for the elo stat (Ranks)

### ISSUE THREAD

**Issue by SuperUser0598** [PluginsTap/BedWars1058-Matchmaking#1]
**Describe the feature that youd'like to add**
Add a rank system for the elo stat in the matchmaking system
add the possibility to create custom ranks and set custom prefixes.

The file format can be:
rankname:
  prefix: "[Silver1]"
  required-elo: 1000-2500 (Range format)

**Additional comments**
Not for now.

**Comment by Mandress101** [comment]
This feature will be added in the next update 👍 

- Close -
